name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - mlflow #=1.14.1
  - jupyterlab #=3.0.10
  - cookiecutter #=1.7.2
  - hydra-core #=1.0.6
  - matplotlib #=3.3.4
  - seaborn #=0.11.1
  - pandas #=1.2.3
  - git #=2.30.2
  - pip #=20.3.3
  - pyyaml #=5.4.1
  - pandas-profiling #=2.11.0
  - black #=21.9
  - pip:
      - wandb #==0.10.31
